[build]
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://ttkh-tourism-backend.onrender.com"

[[redirects]]
  from = "/api/*"
  to = "https://ttkh-tourism-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200