services:
  - type: web
    name: ttkh-tourism-backend
    env: node
    plan: free
    region: singapore
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: ttkh-secret-key-2024-render-auto
      - key: DATABASE_URL
        value: sqlite:./database.sqlite

  - type: static
    name: ttkh-tourism-frontend
    env: static
    plan: free
    region: singapore
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://ttkh-tourism-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html